### ISSUE TITLE
ERROR: UndefVarError: DrakeVisualizer not defined

### ISSUE THREAD

**Issue by weiqiao** [rdeits/DrakeVisualizer.jl#47]
I installed DrakeVisualizer by 
`julia> Pkg.clone("https://github.com/rdeits/DrakeVisualizer.jl.git")`
then when I ran
`julia> DrakeVisualizer.new_window()`
I got error
`ERROR: UndefVarError: DrakeVisualizer not defined`

**Comment by rdeits** [comment]
`Pkg.clone()` or `Pkg.add()` install packages, but do not load them. You need `using DrakeVisualizer` or `import DrakeVisualizer`. See: https://docs.julialang.org/en/stable/manual/modules/
